pipeline {
    agent any
    stages {
        stage('Install') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest'
            }
        }
        stage('Report') {
            steps {
                archiveArtifacts artifacts: 'reports/*.html'
            }
        }
    }
}